name: Generate Golang Vanity Imports
on:
  push:
    tags:
      - 'v*'
    branches:
      - main 
  workflow_dispatch:
jobs:
  generate-golang-vanity-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "noreply@github.com"
      - id: version
        name: Infer version
        run: echo ::set-output name=version::$(cut -d '.' -f 1,2 <<< "${GITHUB_REF#refs/*/}")
      - name: Generate Golang Vanity Imports
        if: steps.version.outputs.version == 'main'
        working-directory: ./
        run: |
          make generate
          git clone https://github.com/revit13/test-vanity-imports.git
          cd test-vanity-imports/
          git checkout origin/gh_actions
          echo "site/ !!!"
          ls site/
          mv site/go-imports/* ../
          echo "ls!!!"
          ls
          git add ../fybrik ../openapi2crd ../crdoc
          git commit -m "Commit for vanity go imports"
          git push origin HEAD:site13
        
