name: Golang Vanity Imports

on:
  repository_dispatch:
    types: [vanity-import-update]

jobs:
  updateVanityImports:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout vanity-imports repository
        uses: actions/checkout@v2
        with:
          path: vanity-imports
      - name: Checkout fybrik repository
        repository: revit13/the-mesh-for-data
        path: fybrik-repo
      - name: Checkout openapi2crd repository
        repository: revit13/openapi2crd
        path: openapi2crd-repo
      - name: Checkout crdoc repository
        repository: revit13/crdoc
        path: crdoc-repo
      - name: Checkout site branch
        uses: actions/checkout@v2
        with:
          repository: revit13/the-mesh-for-data
          path: fybrik-site-branch
          ref: site13
      - run: |
          cp vanity-imports/hack/tools/vangen.sh fybrik-repo
          cd fybrik-repo; ./vangen.sh; cd ..
          cp fybrik-repo/vangen.json vanity-imports/
          make -C vanity-imports generate
          cp vanity-imports/hack/tools/vangen.sh openapi2crd-repo
          cd openapi2crd-repo; ./vangen.sh; cd ..     
          cp openapi2crd-repo/vangen.json vanity-imports/
          make -C vanity-imports generate 
          cp vanity-imports/hack/tools/vangen.sh crdoc-repo
          cd crdoc-repo; ./vangen.sh; cd ..
          cp crdoc-repo/vangen.json vanity-imports/
          make -C vanity-imports generate
          ls vanity-imports/
          ls vanity-imports/vangen
          
          rm -rf fybrik-site-branch/fybrik
          rm -rf fybrik-site-branch/openapi2crd
          rm -rf fybrik-site-branch/crdoc
          make -C vanity-imports generate
          cp -r vanity-imports/vangen/fybrik fybrik-site-branch
          cp -r vanity-imports/vangen/openapi2crd fybrik-site-branch
          cp -r vanity-imports/vangen/crdoc fybrik-site-branch
          ls fybrik-site-branch/
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.VANITY_IMPORTS_ID }}
          private_key: ${{ secrets.VANITY_IMPORTS_PRIVATE_KEY }}
          repository: revit13/the-mesh-for-data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: fybrik-site-branch
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
          title: 'Update vanity imports paths'
          commit-message: "Update vanity imports"
          committer: GitHub <noreply@github.com>
          delete-branch: true

