name: Golang Vanity Imports


on:
  workflow_dispatch:

jobs:
  build:
    name: Golang Vanity Imports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vanity-imports repository
        uses: actions/checkout@v2
        with:
          path: vanity-imports
      - name: Checkout site branch
        uses: actions/checkout@v2
        with:
          repository: revit13/the-mesh-for-data
          path: fybrik-site-branch
          ref: site13
      - run: |
          #rm -rf fybrik-site-branch/fybrik
          #rm -rf fybrik-site-branch/openapi2crd
          #rm -rf fybrik-site-branch/crdoc
          make -C vanity-imports generate
          cp -r vanity-imports/vangen/fybrik fybrik-site-branch
          cp -r vanity-imports/vangen/openapi2crd fybrik-site-branch
          cp -r vanity-imports/vangen/crdoc fybrik-site-branch
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CHARTS_APP_ID }}
          private_key: ${{ secrets.CHARTS_APP_PRIVATE_KEY }}
          repository: revit13/the-mesh-for-data
          ref: site13
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: fybrik-site-branch
          branch: site13
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
          title: 'Update charts to new release'
          commit-message: "Update vanity imports"
          committer: GitHub <noreply@github.com>
          delete-branch: true

